name: women_safety_admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_app_check: ^0.3.2+6
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  get: ^4.7.2
  google_maps_flutter: ^2.12.2
  timeago: ^3.6.0
  photo_view: ^0.14.0
  url_launcher: ^6.3.1
  flutter_phone_direct_caller: ^2.2.1
  google_sign_in: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

